### ISSUE TITLE
Attachments are not showing in the mobile app.

### ISSUE THREAD

**Issue by dtcg** [stefan-niedermann/nextcloud-deck#860]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Attachments are not showing in the mobile app:

| 1 | 2 |
| --- | --- |
| ![Screenshot_2021-03-06-13-59-56-340_it niedermann nextcloud deck](https://user-images.githubusercontent.com/20596421/110207758-f587cd00-7e85-11eb-8fd7-aee6295b6706.png) | ![Screenshot_2021-03-06-14-00-17-838_it niedermann nextcloud deck](https://user-images.githubusercontent.com/20596421/110207762-ff113500-7e85-11eb-87e4-c7cdbe4767ee.png) |

Attachments are docx files, stored on Nextcloud and showing properly on desktop:

![Screenshot_20210306_142258](https://user-images.githubusercontent.com/20596421/110208126-99be4380-7e87-11eb-9bb1-4df9eed0b8f0.png)

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [x] Yes
- [ ] No

**Versions**
 - Nextcloud: https://data.tedomum.net
 - Nextcloud deck : 1.3.0
 - Nextcloud Android Deck: F.droid version 1.14.6

**Smartphone (please complete the following information):**
- Device: Xiaimo redmi 7
- Android-Version: 9
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [ ] No
- [x] no idea

**Comment by desperateCoder** [comment]
Hi @dtcg, thanks for your report! 

> no idea

:laughing: nice one! Then the answer would probably be "no" i guess, no worries!

Could you please try to delete the app data/storage in androids app info and reconnect to your account? I suspect the sync went wrong at some point and now the `etag`s are preventing the card to get synced properly. Alternatively you could try to change something in the description via desktop app and then sync again. 

Please tell us if that fixed the issue for now.

**Comment by dtcg** [comment]
After clearing all app data, it now struggles to connect to the server. I sometimes get blank boards or half the cards showing, weird.
I'm also getting several error messages:

````
App Version: 1.14.6
App Version Code: 1014006
Server App Version: 1.3.0
App Flavor: fdroid

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "<br"
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:135)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "<br"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 17 more

````

````
App Version: 1.14.6
App Version Code: 1014006
Server App Version: 1.3.0
App Flavor: fdroid

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:733)

```

**Comment by dtcg** [comment]
Update: Issue is reproducible with an account from try.nextcloud.com: **yes**

**Comment by desperateCoder** [comment]
> After clearing all app data, it now struggles to connect to the server

Oof, sorry for that! But while having a look at the error messages, from what I can see here, your server seems to be kind of broken... Does the web-UI even still work? I mean see this:

> Not a JSON Object: "<br"

This indicates, that the server answers with some HTML instead of the JSON we requested, that's a huge hint for "your server is broken" or "something other than your server is answering"

I noticed in your screenshot, that you are using a VPN connection (?) 
Maybe something went wrong there? Does it work when you turn VPN off?
 
We both (@stefan-niedermann and me) tested adding attachments and it works well for both of us, so sorry that we need to annoy you with these questions, but I don't see any other way to help you out this situation.

**Comment by dtcg** [comment]
Thanks for your efforts ;)

Same issue without VPN and the web-UI works... I'm clueless.
 
Maybe a version thing...?

**Comment by desperateCoder** [comment]
Well, I'm clueless as well,so I'd suggest building a special, more verbose version only for you. Would be a shame not being able to solve this. Just give me a couple of minutes, I'll comment here soon

**Comment by desperateCoder** [comment]
Here you go: [APK: (≧︿≦)](https://github.com/stefan-niedermann/nextcloud-deck/suites/2198333945/artifacts/45372833)

This is a dev-build, you can install it along your actual version safely, it won't break anything, despite it's already broken :sweat: 

This version will most probably die as well, but also provide a move useful stacktrace, so we can see what the server actually responds. Please see the message before posting here and remove any sensitive data if there is any, I have no clue what the message will actually contain, so just be warned. 

Sorry for the inconveniences though, never seen something like this in our app yet...

Thanks for your cooperation and effort you put into resolving this issue with us! This helps us and other users a lot! :heart:

**Comment by dtcg** [comment]
Done. (I suppose I've neutralised all the sensitive stuff)

````
App Version: 1.14.6
App Version Code: 1014006
Server App Version: 1.3.0
App Flavor: fdroid

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:733)

````
```
App Version: 1.14.6
App Version Code: 1014006
Server App Version: 1.3.0
App Flavor: fdroid

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "<br"
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:135)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "<br"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 17 more

```
```
App Version: 1.14.6
App Version Code: 1014006
Server App Version: 1.3.0
App Flavor: fdroid

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:733)

```
```
App Version: 1.15.0
App Version Code: 1015000
Server App Version: 1.3.0
App Flavor: dev

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

it.niedermann.nextcloud.deck.exceptions.DeckException: (@username: please remove any sensitive data!) Some Malformed stuff here : <br
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:34)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:135)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
```
App Version: 1.15.0
App Version Code: 1015000
Server App Version: 1.3.0
App Flavor: dev

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

it.niedermann.nextcloud.deck.exceptions.DeckException: (@username: please remove any sensitive data!) Some Malformed stuff here : <br
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:34)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:135)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
```
App Version: 1.15.0
App Version Code: 1015000
Server App Version: 1.3.0
App Flavor: dev

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

it.niedermann.nextcloud.deck.exceptions.DeckException: (@username: please remove any sensitive data!) Some Malformed stuff here : <br
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:34)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:135)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
```
App Version: 1.15.0
App Version Code: 1015000
Server App Version: 1.3.0
App Flavor: dev

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
		Nextcloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/apps/theming/manifest?v=54">
		<link rel="stylesheet" href="/core/css/guest.css?v=c2aedc67-54">
		<script nonce="YVBMcEY1dnFhSVlGZlBPYWFocGJCTHQ1R2owMUJqMlFrYVRZckpzbDQzaz06SEppTFQ5K2NSL3hYTExiTk1sYy9iK2tMTVV0UWZFKzd4dE9BNy9CcWhFcz0=" defer src="/core/js/dist/main.js?v=c2aedc67-54"></script>
<script nonce="YVBMcEY1dnFhSVlGZlBPYWFocGJCTHQ1R2owMUJqMlFrYVRZckpzbDQzaz06SEppTFQ5K2NSL3hYTExiTk1sYy9iK2tMTVV0UWZFKzd4dE9BNy9CcWhFcz0=" defer src="/core/js/dist/files_fileinfo.js?v=c2aedc67-54"></script>
<script nonce="YVBMcEY1dnFhSVlGZlBPYWFocGJCTHQ1R2owMUJqMlFrYVRZckpzbDQzaz06SEppTFQ5K2NSL3hYTExiTk1sYy9iK2tMTVV0UWZFKzd4dE9BNy9CcWhFcz0=" defer src="/core/js/dist/files_client.js?v=c2aedc67-54"></script>
<script nonce="YVBMcEY1dnFhSVlGZlBPYWFocGJCTHQ1R2owMUJqMlFrYVRZckpzbDQzaz06SEppTFQ5K2NSL3hYTExiTk1sYy9iK2tMTVV0UWZFKzd4dE9BNy9CcWhFcz0=" defer src="/js/core/merged-template-prepend.js?v=c2aedc67-54"></script>
			</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									Nextcloud								</h1>
																	<img src="/core/img/logo/logo.svg?v=016dc74cf0108f4ac150109424616e79947d1a33"/>
															</div>
						</div>
					</header>
								<main>
					<div class="error error-wide">
	<h2>Internal Server Error</h2>
	<p>The server was unable to complete your request.</p>
	<p>If this happens again, please send the technical details below to the server administrator.</p>
	<p>More details can be found in the server log.</p>

	<h3>Technical details</h3>
	<ul>
		<li>Remote Address: 93.23.107.52</li>
		<li>Request ID: j3hs4ObBPVdbwLd58yvv</li>
			</ul>

	</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener">Nextcloud</a> – a safe home for all your data			</p>
		</footer>
	</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:733)

```
```
App Version: 1.15.0
App Version Code: 1015000
Server App Version: 1.3.0
App Flavor: dev

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
		Nextcloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/apps/theming/manifest?v=54">
		<link rel="stylesheet" href="/core/css/guest.css?v=c2aedc67-54">
		<script nonce="aDdVTE9mbVIyekV0NXBSOUZ3TGJZT241bnhLVk1xR3g5RzhxempiZUI0Zz06dm9adlQ1K2s0MFI5bnZ3clEwK1ZMWkRXMWtEdlVPYnJyUWhnOWxxUFpyRT0=" defer src="/core/js/dist/main.js?v=c2aedc67-54"></script>
<script nonce="aDdVTE9mbVIyekV0NXBSOUZ3TGJZT241bnhLVk1xR3g5RzhxempiZUI0Zz06dm9adlQ1K2s0MFI5bnZ3clEwK1ZMWkRXMWtEdlVPYnJyUWhnOWxxUFpyRT0=" defer src="/core/js/dist/files_fileinfo.js?v=c2aedc67-54"></script>
<script nonce="aDdVTE9mbVIyekV0NXBSOUZ3TGJZT241bnhLVk1xR3g5RzhxempiZUI0Zz06dm9adlQ1K2s0MFI5bnZ3clEwK1ZMWkRXMWtEdlVPYnJyUWhnOWxxUFpyRT0=" defer src="/core/js/dist/files_client.js?v=c2aedc67-54"></script>
<script nonce="aDdVTE9mbVIyekV0NXBSOUZ3TGJZT241bnhLVk1xR3g5RzhxempiZUI0Zz06dm9adlQ1K2s0MFI5bnZ3clEwK1ZMWkRXMWtEdlVPYnJyUWhnOWxxUFpyRT0=" defer src="/js/core/merged-template-prepend.js?v=c2aedc67-54"></script>
			</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									Nextcloud								</h1>
																	<img src="/core/img/logo/logo.svg?v=016dc74cf0108f4ac150109424616e79947d1a33"/>
															</div>
						</div>
					</header>
								<main>
					<div class="error error-wide">
	<h2>Internal Server Error</h2>
	<p>The server was unable to complete your request.</p>
	<p>If this happens again, please send the technical details below to the server administrator.</p>
	<p>More details can be found in the server log.</p>

	<h3>Technical details</h3>
	<ul>
		<li>Remote Address: 93.23.107.52</li>
		<li>Request ID: yVqxkGrKJUNwwVyXRlfV</li>
			</ul>

	</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener">Nextcloud</a> – a safe home for all your data			</p>
		</footer>
	</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:733)

```
```
App Version: 1.15.0
App Version Code: 1015000
Server App Version: 1.3.0
App Flavor: dev

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:733)

```
```
App Version: 1.15.0
App Version Code: 1015000
Server App Version: 1.3.0
App Flavor: dev

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:733)

```
```
App Version: 1.15.0
App Version Code: 1015000
Server App Version: 1.3.0
App Flavor: dev

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:733)

```

**Comment by dtcg** [comment]
I guess their server is under maintenance or something.

**Comment by desperateCoder** [comment]
@dtcg we actually handle maintenance already very well... We display an according message in this case. Seeing all those messages made me die inside a little, I think I need to sleep over this. As mentioned, I never saw something similar in the entire history of this app. What really makes me curious: 

> Server App Version: 1.3.0

I don't know, but my NC-instance is up to date and I just have the Deck-Webapp at `1.2.5`. Your server apparently lives in 2030... No clue whats going on here... I guess I'll need to enhance the error message by providing a bunch of further information.

Just a quick question: what exactly did you do, to get this HUGE load of error messages? Did they come up all at once? I'm confused....

**Comment by dtcg** [comment]
> Just a quick question: what exactly did you do, to get this HUGE load of error messages? Did they come up all at once? I'm confused....

I just tried to connect ;) and then the first message appeared. As I tapped "copy", the code seemed to change, so I carried on copying from the app and pasting into separate text files. I had to repeat this about 10 times so I'm actually not sure some messages aren't duplicates... I did find it weird it wasn't one consolidated error log but there you go.

> Your server apparently lives in 2030...

It is hosted on some FOSS French association: https://www.tedomum.net you can create a free account for sake of testing.
Instance URL: https://data.tedomum.net

They seem to be experiencing issues with the Circles app and sharing capabilities at the minute: https://mastodon.tedomum.net/@tedomum

**Comment by desperateCoder** [comment]
Any chance, that the context root of your Nextcloud instance has changed? I saw they updated some stuff but the Circles app still won't work - but thats fine, we don't depend on that. 

Could you upload a file via web-UI into the files app and synchronize your android files app to see, if it is shown there? I suspect the connection between your files app and your server to break it... something is wrong with either the connection or the server.

I guess you don't have these connection problems with the account from `try.nextcloud.com`, right?

**Comment by stefan-niedermann** [comment]
I have been able to reproduce the original issue (attachments being not visible) - seems to be a bug with the deck server app 1.3.0+. Regarding the other error messages i also believe that there was some kind of migration or misconfiguration of your instance. Those are unrelated to the actual issue IMHO.

**Comment by dtcg** [comment]
More testing :

data.tedomum.net (instance under maintenance) 
* connection : throws the many error messages posted earlier 

Framadrive.org (another instance I'm using)
* connection : OK
* upload attachment from phone app: OK
* upload attachment from web app : OK

demo1.nextcloud.com 
* connection: OK
* upload attachment from phone app : OK
* upload attachment from web app : OK

demo2.nextcloud.com
* connection : throws error below but still connects 
* upload attachment from phone app : OK
* upload attachment from web app : sometimes syncs to phone app, sometimes doesn't... 

````
App Version: 1.14.6
App Version Code: 1014006
Server App Version: 1.2.4
App Flavor: fdroid

Files App Version Code: 30150090

---

OS Version: 4.9.112-perf+(V10.3.1.0.PFLEUXM)
OS API Level: 28
Device: onc
Manufacturer: Xiaomi
Model (and Product): Redmi 7 (onc_eea)

---

java.lang.IllegalArgumentException: NextcloudArrayDeserializer got a Json Object, fallback parsing failed for input: {"51559":{"title":"Personal","owner":{"primaryKey":"YejCYMfMYRxAkxxM","uid":"YejCYMfMYRxAkxxM","displayname":"YejCYMfMYRxAkxxM","type":0},"color":"0087C5","archived":false,"labels":[{"title":"Finished","color":"31CC7C","boardId":51559,"cardId":null,"lastModified":1615236691,"id":206369,"ETag":"a510d16727b21c153cd67783024b2e6f"},{"title":"To review","color":"317CCC","boardId":51559,"cardId":null,"lastModified":1615236691,"id":206370,"ETag":"a510d16727b21c153cd67783024b2e6f"},{"title":"Action needed","color":"FF7A66","boardId":51559,"cardId":null,"lastModified":1615236691,"id":206371,"ETag":"a510d16727b21c153cd67783024b2e6f"},{"title":"Later","color":"F1DB50","boardId":51559,"cardId":null,"lastModified":1615236691,"id":206372,"ETag":"a510d16727b21c153cd67783024b2e6f"}],"acl":[],"permissions":{"PERMISSION_READ":true,"PERMISSION_EDIT":true,"PERMISSION_MANAGE":true,"PERMISSION_SHARE":true},"users":[{"primaryKey":"YejCYMfMYRxAkxxM","uid":"YejCYMfMYRxAkxxM","displayname":"YejCYMfMYRxAkxxM","type":0}],"stacks":[],"deletedAt":0,"lastModified":1615236691,"settings":{"notify-due":"assigned","calendar":true},"id":51559,"ETag":"a510d16727b21c153cd67783024b2e6f"}}
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:42)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:135)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

````

**Comment by desperateCoder** [comment]
@dtcg thanks for the great research! We'll have a look.:heart:

**Comment by stefan-niedermann** [comment]
I debugged the issue and it's definitely a server error of Deck 1.3.0+.

I [opened an issue in their repository](https://github.com/nextcloud/deck/issues/2874) - nothing we can fix on our side, unfortunately. I'd suggest you to subscribe to it and upvote the issue.

Thank you for the detailed reports though and the hard work you put in there to support us finding the root cause :slightly_smiling_face:
