### ISSUE TITLE
Database migration errors in 1.17.x

### ISSUE THREAD

**Issue by Killerjoe** [stefan-niedermann/nextcloud-deck#935]
**Describe the bug**
Crash on Startup with Nextcloud Deck 1.17.4 Beta

1. Open Nextcloud Deck
2. See the attached Exception

**Expected behavior**
No crash on Startup

**Screenshots**
Not available

**Versions**
 - Nextcloud: 21.0.1
 - Nextcloud Deck: 1.4 and latest 1.3.x same behaviour
 - Nextcloud Android: 3.15.1
 - Nextcloud Android Deck: 1.17.4

**Smartphone (please complete the following information):**
- Device: Samsung Note 10 Plus
- Android-Version: 10
- App-Store:
  - [ x ] Google Play Store (Beta channel)

**Stacktrace**

```
Full Crash:

App Version: 1.17.4
App Version Code: 1017004
App Flavor: play

Files App Version Code: 30150190

---

OS Version: 4.14.113-20606106(N975FXXS6EUCA)
OS API Level: 30
Device: d2s
Manufacturer: samsung
Model (and Product): SM-N975F (d2seea)

---

java.lang.RuntimeException: Exception while computing database live data.
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Activity_tmp.type (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1164)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2438)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2359)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.migration.Migration_30_31.migrate(Migration_30_31.java:31)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:99)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:177)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:489)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
	at androidx.room.util.DBUtil.query(DBUtil.java:83)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:276)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:273)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
	... 3 more

```

**Comment by stefan-niedermann** [comment]
Do you know drom which version did you update? Have you installed `17.1.2` or `17.1.3`?

**Comment by Killerjoe** [comment]
Good question. I dont know the exact number, but I think it was 1.16.3.

**Comment by stefan-niedermann** [comment]
We think we have found a solution for this quite weird state...

Could i ask you to send me an email at info@niedermann.it with a link to this issue so i can send you a test apk which should fix this issue?

**Comment by Killerjoe** [comment]
Can you release a new Beta as it seems the bug was found or should I still send you an email to get a test apk?

**Comment by desperateCoder** [comment]
Please still mail him, we got a weird constellation here, we'd like tu ensure, that our solution really works. Your constellation shouldn't exist, but still seems to. We just want to make sure, would be great if you could do us this favor!

**Comment by Killerjoe** [comment]
Ok, I've sent him an email. I will wait for the apk and will test the fix for you.

**Comment by Killerjoe** [comment]
I just saw that you have released 1.17.5 via Playstore but the issue is still there.

```
Full Crash:

App Version: 1.17.5
App Version Code: 1017005
App Flavor: play

Files App Version Code: 30150190

---

OS Version: 4.14.113-20606106(N975FXXS6EUCA)
OS API Level: 30
Device: d2s
Manufacturer: samsung
Model (and Product): SM-N975F (d2seea)

---

java.lang.RuntimeException: Exception while computing database live data.
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Activity_tmp.type (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1164)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2438)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2359)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.migration.Migration_30_31.migrate(Migration_30_31.java:33)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:99)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:177)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:489)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
	at androidx.room.util.DBUtil.query(DBUtil.java:83)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:276)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:273)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
	... 3 more

```

**Comment by Killerjoe** [comment]
Thanks for apk 1.17.6 but I still get an exception after starting the app.

```
Full Crash:

App Version: 1.17.6
App Version Code: 1017006
App Flavor: play

Files App Version Code: 30150190

---

OS Version: 4.14.113-20606106(N975FXXS6EUCA)
OS API Level: 30
Device: d2s
Manufacturer: samsung
Model (and Product): SM-N975F (d2seea)

---

java.lang.RuntimeException: Exception while computing database live data.
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Card_tmp.archived (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1164)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2438)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2359)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.migration.Migration_30_31.migrate(Migration_30_31.java:64)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:99)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:177)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:489)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
	at androidx.room.util.DBUtil.query(DBUtil.java:83)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:276)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:273)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
	... 3 more

```

**Comment by desperateCoder** [comment]
Aw c'mon! At least we got a little further...

Big thanks for testing @Killerjo! I'll fix this one as well tomorrow!

**Comment by stefan-niedermann** [comment]
@Killerjoe & @creywood please test `1.17.7`? (Available at the beta channel right now)

**Comment by creywood** [comment]
> please test `1.17.7`? (Available at the beta channel right now)

Unfortunately I'm running the f-droid build (and am assuming as a result that testing the Google Play beta wouldn't verify the migration of my data? Maybe I'm wrong there?). Very happy to test an APK that would have access to my data. FYI waking hours are running short here.

**Comment by stefan-niedermann** [comment]
@creywood no you are right, doesn't make sense in your case, you'll have to wait for th F-Droid build unfortunately. Thanks for the responsey though!

**Comment by creywood** [comment]
> @creywood no you are right, doesn't make sense in your case, you'll have to wait for th F-Droid build unfortunately. Thanks for the responsey though!

Ok no worries. A question down that path: presuming the bug is fixed during the night, is there a way for me to end up with an APK on my device that a) can access my existing device data and b) I can later update when f-droid catches up, so that I don't have to wait another 24hr? eg. rolling my own build? Thanks, and sorry for the tangent :slightly_smiling_face:

**Comment by Killerjoe** [comment]
Thank you for 1.17.7 it seems the bug is finally fixed. Deck was starting normal and is usable again.

**Comment by stefan-niedermann** [comment]
> Thank you for 1.17.7 it seems the bug is finally fixed. Deck was starting normal and is usable again.

@Killerjoe thank you very much for reporting and testing! Glad to hear that we were able to iron out this tricky bug!

**Comment by stefan-niedermann** [comment]
> presuming the bug is fixed during the night, is there a way for me to end up with an APK on my device that a) can access my existing device data and b) I can later update when f-droid catches up, so that I don't have to wait another 24hr? eg. rolling my own build? Thanks, and sorry for the tangent :slightly_smiling_face: 

Unfortunately i can not build you an `APK` file which is compatible with the installed from F-Droid as they would be signed with a different key and can therefore not directly replace each other.

Your options are:
1. Wait for F-Droid to build the version with the fix (will keep unsynchronized data)
2. [Clear the storage](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) of the Deck app and reimport your account (will remove unsynchronized data)
3. Install and use [this dev build](https://github.com/stefan-niedermann/nextcloud-deck/suites/2502152739/artifacts/54053959) temporarily (it can be installed safely parallel to the F-Droid version) until F-Droid provides the version with the fix. Your unsynchronized changes will only be available after F-Droid provides the version with the fix (`1.17.7`) but you will be able to continue working from your smartphone for now

Choose option 1. or 3. if you do have any unsynchronized changes, option 2. only in case you are sure that everything is up to date also in the Web UI.

**Comment by creywood** [comment]
Thanks for the detailed explanation @stefan-niedermann :+1: I thought/feared that might be the case. I'm looking to get the unsynchronised local data so I'll wait.
